### PR TITLE
Avoid some warnings

### PR DESCRIPTION
**Pull request by GregThib**
These warnings appears now in the log console of TT-RSS. So, this is the fix.

### CODE REVIEW

**Comment by mr-flibble** [comment]
Hello @GregThib 
If I use version from this pull request, then on ios  Fiery Feeds app, only latest 20 unread articles are synced to app. So its not very usable :)

**Comment by GregThib** [comment]
> 
> 
> Hello @GregThib
> If I use version from this pull request, then on ios Fiery Feeds app, only latest 20 unread articles are synced to app. So its not very usable :)



> 
> 
> Hello @GregThib
> If I use version from this pull request, then on ios Fiery Feeds app, only latest 20 unread articles are synced to app. So its not very usable :)

**Comment by GregThib** [comment]
Changed that!
What is Fiery Feeds ? This plugin is for Newsplus app, whose set the limit value in the request.
Is it a Newsplus fork ?

**Comment by mr-flibble** [comment]
Thanks, i will try that tomorrow.

Fiery Feeds is ios reader app ( https://apps.apple.com/us/app/fiery-feeds-rss-reader/id1158763303 ) with support for [News+ API for Tiny Tiny RSS](http://blog.cocoacake.net/fiery-feeds-user-guide)

**Comment by hrk** [comment]
Thank you very much and sorry for the delay!

**Pull request merged**
